# Generated by Django 3.1.7 on 2021-03-18 03:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
